name: "Pull Request Preview Build"
on: pull_request

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Test
        run: echo $GITHUB_SHA_SHORT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: print SHA
        run: echo ${{ env.GITHUB_SHA_SHORT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caladreas/cmg:latest,caladreas/cmg:${{ env.GITHUB_SHA_SHORT }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
